services:
  nginx:
    build:
      context: .
      dockerfile: ./_docker/nginx/Dockerfile
    container_name: nginx_go
    ports:
      - "8000:80"
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - go
    restart: unless-stopped
    depends_on:
      - go

  mysql:
    image: mysql:8.2.0
    container_name: mysql_go
    restart: always
    volumes:
      - ./_docker/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --log_bin_trust_function_creators=1
    env_file:
      - ./_docker/mysql/mysql.env
    networks:
      - go

  go:
    build:
      context: .
      dockerfile: _docker/go/Dockerfile
    container_name: go_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["air", "-c", ".air.toml"]
    ports:
      - "8080:8080"
    networks:
      - go
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - mysql

  redis:
    image: redis:latest
    container_name: redis_go
    ports:
      - "6379:6379"
    networks:
      - go
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_go
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 100000000
    restart: always
    ports:
      - "8081:80"
    networks:
      - go

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_go
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - go
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

volumes:
  db_data:
  es_data:

networks:
  go:
    driver: bridge
